# Generated by Django 4.1.5 on 2023-01-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='media')),
                ('food_name', models.CharField(max_length=200)),
                ('restaurant_name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('review', models.PositiveIntegerField(default=3, null=True)),
                ('free_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20)),
            ],
        ),
    ]
