# Generated by Django 4.1.5 on 2023-01-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contents',
        ),
    ]
