# Generated by Django 4.1.5 on 2023-01-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.CharField(default=3000, max_length=200),
        ),
    ]
