# Generated by Django 4.1.5 on 2023-01-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_article_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='free_text',
            field=models.CharField(default='おいしかったです。', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='place',
            field=models.CharField(default='池袋', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='restaurant_name',
            field=models.CharField(default='未入力', max_length=200),
        ),
    ]
